[pytest]
# Путь к тестам
testpaths = tests 

# Мин. % покрытия
addopts = --cov=app --cov-report=term --cov-report=html --cov-fail-under=60 

# Игнорируем warnings
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning